# Generated by Django 3.2.4 on 2021-12-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
            ],
        ),
    ]
