# Generated by Django 3.2.4 on 2021-12-28 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0003_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newProduct.height'),
        ),
        migrations.AddField(
            model_name='variants',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newProduct.height'),
        ),
    ]
