# Generated by Django 3.2.4 on 2022-02-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0008_alter_product_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'verbose_name_plural': 'Sub_subcategories'},
        ),
        migrations.AlterModelOptions(
            name='unittypes',
            options={'verbose_name_plural': 'Unit_Types'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': 'Variants'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='newProduct.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Weight', 'Weight'), ('Length', 'Length'), ('Width', 'Width'), ('Size-Color', 'Size-Color'), ('Wght-Color', 'Weight-Color')], default='None', max_length=10),
        ),
    ]
