# Generated by Django 3.2.4 on 2022-02-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0009_alter_comment_product'),
        ('newProduct', '0010_alter_product_variant'),
    ]

    operations = [
    ]
