# Generated by Django 3.2.4 on 2022-05-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0013_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spare_parts',
            field=models.BooleanField(default=False),
        ),
    ]
