# Generated by Django 3.2.4 on 2022-05-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0040_itemimage'),
        ('newProduct', '0014_product_spare_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.engine'),
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.make'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.item_model'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.year'),
        ),
    ]
