# Generated by Django 3.2.4 on 2022-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0015_auto_20220518_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spare_number',
            field=models.IntegerField(default=0),
        ),
    ]
