# Generated by Django 3.2.4 on 2022-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0016_product_spare_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
