# Generated by Django 3.2.4 on 2022-06-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0017_product_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
