# Generated by Django 3.2.4 on 2022-06-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0018_adjacentcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='adjacent_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adjacent_color', to='newProduct.adjacentcolor'),
        ),
    ]
