# Generated by Django 3.2.4 on 2022-07-05 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0020_auto_20220629_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentColorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Discount %')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='adjacentcolor',
            name='parent_color',
        ),
        migrations.AddField(
            model_name='variants',
            name='have_adjacent_color',
            field=models.BooleanField(default=False),
        ),
    ]
