# Generated by Django 3.2.4 on 2022-07-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0021_auto_20220705_1214'),
        ('ordering', '0028_auto_20220705_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdjacentColor',
        ),
        migrations.AddField(
            model_name='adjacentcolorproduct',
            name='parent_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adjacent_color', to='newProduct.color'),
        ),
        migrations.AddField(
            model_name='adjacentcolorproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_product_variant', to='newProduct.variants'),
        ),
    ]
