# Generated by Django 3.2.4 on 2022-07-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0022_auto_20220705_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjacentcolorproduct',
            name='parent_color',
        ),
    ]
