# Generated by Django 3.2.4 on 2022-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0023_remove_adjacentcolorproduct_parent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacentcolorproduct',
            name='is_vat',
            field=models.BooleanField(default=True),
        ),
    ]
