# Generated by Django 3.2.4 on 2022-07-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0024_adjacentcolorproduct_is_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjacentcolorproduct',
            name='code',
        ),
        migrations.AddField(
            model_name='adjacentcolorproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newProduct.color'),
        ),
    ]
