# Generated by Django 3.2.4 on 2022-07-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0025_auto_20220713_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacentcolorproduct',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
