# Generated by Django 3.2.4 on 2022-07-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0026_adjacentcolorproduct_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjacentcolorproduct',
            old_name='name',
            new_name='title',
        ),
    ]
