# Generated by Django 3.2.4 on 2022-07-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0027_rename_name_adjacentcolorproduct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_colo_images', to='newProduct.adjacentcolorproduct'),
        ),
    ]
