# Generated by Django 3.2.4 on 2022-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0029_alter_productimage_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacentcolorproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
