# Generated by Django 3.2.4 on 2022-07-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0031_product_have_adjacent_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='have_adjacent_color',
        ),
    ]
