# Generated by Django 3.2.4 on 2022-07-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0013_auto_20220412_1137'),
        ('newProduct', '0032_remove_product_have_adjacent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacentcolorproduct',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_color_vendor', to='vendor.vendor'),
        ),
    ]
