# Generated by Django 3.2.4 on 2022-03-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('review', models.BooleanField(default=False)),
                ('tin', models.CharField(default=0, max_length=255)),
                ('account', models.CharField(choices=[('individual', 'individual'), ('company', 'company')], default='individual', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.category')),
            ],
        ),
    ]
