# Generated by Django 3.2.4 on 2022-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220401_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='account',
            field=models.CharField(choices=[('individual', 'individual'), ('company', 'company')], max_length=20),
        ),
    ]
