# Generated by Django 3.2.4 on 2022-04-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20220401_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='account',
            field=models.CharField(choices=[('COMPANY', 'company'), ('INDIVIDUAL', 'individual')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category'),
        ),
    ]
