# Generated by Django 3.2.4 on 2022-04-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20220420_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.experience'),
        ),
    ]
