# Generated by Django 3.2.4 on 2022-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_serviceprovider_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.CharField(max_length=255)),
            ],
        ),
    ]
