# Generated by Django 3.2.4 on 2022-04-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='daily_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_daily_rate', to='services.daily_rate'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
