# Generated by Django 3.2.4 on 2022-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20220425_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
