# Generated by Django 3.2.4 on 2022-02-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Mobile_operator',
        ),
    ]
