# Generated by Django 3.2.4 on 2022-02-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_payment_mobile_operator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile_operator',
            new_name='MobileOperator',
        ),
    ]
