# Generated by Django 3.2.4 on 2022-03-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20220323_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_renting',
        ),
    ]
