# Generated by Django 3.2.4 on 2022-03-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rename_category_category_renting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_renting',
            new_name='Category',
        ),
    ]
