# Generated by Django 3.2.4 on 2022-03-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rename_category_renting_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
