# Generated by Django 3.2.4 on 2022-03-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20220323_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
