# Generated by Django 3.2.4 on 2022-03-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0012_alter_brand_options'),
        ('rental', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriprion', models.TextField(max_length=255)),
                ('price', models.DateTimeField(default=0, max_length=12)),
                ('contact', models.TextField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_unit', to='newProduct.unittypes')),
            ],
        ),
    ]
