# Generated by Django 3.2.4 on 2022-03-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0012_alter_brand_options'),
        ('rental', '0008_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
