# Generated by Django 3.2.4 on 2022-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_rename_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
