# Generated by Django 3.2.4 on 2022-03-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriprion',
            new_name='description',
        ),
    ]
