# Generated by Django 3.2.4 on 2022-03-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0012_alter_openinghours_unique_together'),
        ('rental', '0011_rename_descriprion_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
