# Generated by Django 3.2.4 on 2022-03-24 11:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_item_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='slugV',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='vendor'),
        ),
    ]
