# Generated by Django 3.2.4 on 2022-03-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_auto_20220324_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Unit_Types',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slugV',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_item', to='rental.unittypes'),
        ),
    ]
