# Generated by Django 3.2.4 on 2022-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
