# Generated by Django 3.2.4 on 2022-03-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_item_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
    ]
