# Generated by Django 3.2.4 on 2022-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_remove_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
