# Generated by Django 3.2.4 on 2022-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
