# Generated by Django 3.2.4 on 2022-04-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_mobile_operator_mobileoperator'),
        ('rental', '0025_item_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.district'),
        ),
    ]
