# Generated by Django 3.2.4 on 2022-04-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_auto_20220419_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Makes',
            new_name='Make',
        ),
    ]
