# Generated by Django 3.2.4 on 2022-04-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0028_rename_makes_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='name',
            new_name='make',
        ),
    ]
