# Generated by Django 3.2.4 on 2022-04-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0033_subcategory_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='rental.type'),
        ),
    ]
