# Generated by Django 3.2.4 on 2022-04-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0034_auto_20220426_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='description',
        ),
        migrations.RemoveField(
            model_name='type',
            name='image',
        ),
    ]
