# Generated by Django 3.2.4 on 2022-04-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0036_auto_20220426_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_model', to='rental.item_model'),
        ),
    ]
