# Generated by Django 3.2.4 on 2022-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0037_auto_20220426_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sale',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
