# Generated by Django 3.2.4 on 2022-04-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0038_alter_item_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
