# Generated by Django 3.2.4 on 2022-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_alter_orderitem_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_no_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
