# Generated by Django 3.2.4 on 2022-01-11 12:34

import apps.ordering.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_orderitem_price_no_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_code',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(default=apps.ordering.utils.create_new_ref_number, max_length=100),
        ),
    ]
