# Generated by Django 3.2.4 on 2022-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='momo',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
