# Generated by Django 3.2.4 on 2022-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_order_momo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('shipped', 'Shipped'), ('arrived', 'Arrived')], default='waiting', max_length=20),
        ),
    ]
