# Generated by Django 3.2.4 on 2022-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_provider',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
