# Generated by Django 3.2.4 on 2022-01-08 12:14

import apps.ordering.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0010_auto_20220108_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, default=apps.ordering.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(default=apps.ordering.utils.create_new_ref_number, max_length=100),
        ),
    ]
