# Generated by Django 3.2.4 on 2022-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_order_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('shipped', 'Shipped'), ('arrived', 'Arrived')], default='pending', max_length=20),
        ),
    ]
