# Generated by Django 3.2.4 on 2022-05-31 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0040_itemimage'),
        ('ordering', '0012_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quatation_item', to='rental.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quatation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
