# Generated by Django 3.2.4 on 2022-05-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0016_product_spare_number'),
        ('ordering', '0013_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='item',
        ),
        migrations.AddField(
            model_name='quotation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quatation_item', to='newProduct.product'),
        ),
    ]
