# Generated by Django 3.2.4 on 2022-05-31 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordering', '0014_auto_20220531_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quatation_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
