# Generated by Django 3.2.4 on 2022-05-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0016_quotation_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='vendor',
        ),
    ]
