# Generated by Django 3.2.4 on 2022-05-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0013_auto_20220412_1137'),
        ('ordering', '0017_remove_quotation_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quataion_vendor', to='vendor.vendor'),
        ),
    ]
