# Generated by Django 3.2.4 on 2022-05-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0018_quotation_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reference',
            field=models.IntegerField(default=0),
        ),
    ]
