# Generated by Django 3.2.4 on 2022-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0020_rename_reference_quotation_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
