# Generated by Django 3.2.4 on 2022-06-02 09:52

import apps.ordering.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0021_quotation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='reference_number',
            field=models.CharField(default=apps.ordering.utils.create_new_ref_number, max_length=100),
        ),
    ]
