# Generated by Django 3.2.4 on 2022-06-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0022_alter_quotation_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
