# Generated by Django 3.2.4 on 2022-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0023_auto_20220606_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='engine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='part_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
