# Generated by Django 3.2.4 on 2022-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0024_auto_20220606_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='year',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
