# Generated by Django 3.2.4 on 2022-06-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0025_alter_quotation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
