# Generated by Django 3.2.4 on 2022-06-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0020_auto_20220629_1127'),
        ('ordering', '0026_alter_quotation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newProduct.adjacentcolor'),
        ),
    ]
