# Generated by Django 3.2.4 on 2022-07-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0021_auto_20220705_1214'),
        ('ordering', '0027_shopcart_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='color',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='variant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newProduct.adjacentcolorproduct'),
        ),
    ]
