# Generated by Django 3.2.4 on 2022-07-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newProduct', '0024_adjacentcolorproduct_is_vat'),
        ('ordering', '0028_auto_20220705_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='newProduct.adjacentcolorproduct'),
        ),
    ]
