# Generated by Django 3.2.4 on 2022-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0031_alter_orderitem_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_variant_color',
            field=models.BooleanField(default=False),
        ),
    ]
